[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "for _, card in ipairs(context.cardarea.cards) do"
position = "before"
payload = "local curcards = Quantum.processCards(context)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for _, area in ipairs(SMODS.get_card_areas('jokers')) do for _, _card in ipairs(area.cards) do"
position = "at"
payload = "local areas = Quantum.processArea(SMODS.get_card_areas('jokers')); for _, area in ipairs(areas) do local curcards = Quantum.processArea(area.cards); for _, _card in ipairs(curcards) do"
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for _, area in ipairs(SMODS.get_card_areas('jokers')) do for _, _card in ipairs(area.cards) do"
position = "at"
payload = "local areas = Quantum.processArea(SMODS.get_card_areas('jokers')); for _, area in ipairs(areas) do local curcards = Quantum.processArea(area.cards); for _, _card in ipairs(curcards) do"
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """       elseif _c.name == "The World" then loc_vars = {cfg.max_highlighted, localize(cfg.suit_conv, 'suits_plural'), colours = {G.C.SUITS[cfg.suit_conv]}}
       end
       localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}"""
position = "before"
payload = """
elseif _c.set == 'QuantumDescriptionDummy' then
    localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = """if not hand_space then
        local limit = G.hand.config.card_limit - #G.hand.cards
        local unfixed = not G.hand.config.fixed_limit
        local n = 0
        while n < #G.deck.cards do
            local card = G.deck.cards[#G.deck.cards-n]"""
position = "after"
payload = """
if  G.GAME.modifiers.quantum_nightmare and #(SMODS.get_enhancements(card)) < 1 then
if SMODS.pseudorandom_probability(self, 'nightmare_ cards', 1, 3) then
    card:set_ability(G.P_CENTERS["m_stone"])
end
end
"""
match_indent = true
